#options:
#  logging: CLOUD_LOGGING_ONLY
#
#steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prediction', '.']
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/prediction']
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['run', 'deploy', 'your-model-service', '--image', 'gcr.io/$PROJECT_ID/prediction', '--platform', 'managed', '--region', 'us-west2']
#
#images:
#  - 'gcr.io/$PROJECT_ID/prediction'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prediction:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prediction:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'get-prediction'  # Replace with your service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/prediction:$BUILD_ID'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west2'
      - '--allow-unauthenticated'  # Enable unauthenticated access

images:
  - 'gcr.io/$PROJECT_ID/prediction:$BUILD_ID'
