steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/prediction', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/prediction']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'your-model-service', '--image', 'gcr.io/$PROJECT_ID/prediction', '--platform', 'managed']

images:
  - 'gcr.io/$PROJECT_ID/prediction'
